name: Cherry-pick merged PRs to specified branches

on:
  pull_request:
    types: [closed]

jobs:
  cherry-pick-to-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Determine cherry-pick branches
        id: get-cherry-pick-branches
        run: |
          BRANCHES=""
          for tag in ${{ github.event.pull_request.labels.*.name }} | grep -o 'chpick:[^ ,]\+' | cut -d: -f2-); do
            BRANCHES="$BRANCHES $tag"
          done
          echo "BRANCHES=\"($BRANCHES)\"" >> $GITHUB_OUTPUT

      - name: Cherry-pick to branch
        run: |
          for BRANCH in ${{ steps.get-cherry-pick-branches.outputs.BRANCHES }}; do
            git checkout -b "${{ github.event.pull_request.head.ref }}-to-$BRANCH" main
            git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }}
            git push origin "${{ github.event.pull_request.head.ref }}-to-$BRANCH" -f
            hub pull-request --base $BRANCH --draft --no-edit --push --message "cherry-pick: ${{ github.event.pull_request.title }}" --assignee "${{ github.event.pull_request.user.login }}"
          done
